### ISSUE TITLE
Chevron icon out of black circle

### ISSUE THREAD

**Issue by WhiteWolfSix** [marcosegato/grav-plugin-backtotop#3]
Hi, after installation of this plugin I found it working with one small issue. Chevron icon is out of a black circle then on white background you see circle with no chevron icon, on dark background you see it out of the circle. I am using Landio v1.4.0 theme.
![ChevronIconBug](https://user-images.githubusercontent.com/24316177/82923758-b4b86a80-9f7b-11ea-8531-093183a2c126.jpg)

**Comment by marcosegato** [comment]
Hi, is there any public website I can quickly check without installing in my local that custom theme?
Thanks

**Comment by WhiteWolfSix** [comment]
Hi Marco, unfortunately the website is on localhost at the moment. Thanks

**Comment by WhiteWolfSix** [comment]
Public version:
http://www.annwin.eu/

**Comment by marcosegato** [comment]
This issue is cause by landio.css stylesheet used in your custom theme.
line 5099: text-align: right;
line 5096: text-align: center;
Once removed/commented, it works fine.
