### ISSUE TITLE
Back to top showing but don't working

### ISSUE THREAD

**Issue by alfabuster** [marcosegato/grav-plugin-backtotop#5]
It is really strange thing, but this is it. I installed plugin using admin. Now I use mediator theme and put code 
`{% if config.plugins.backtotop.enabled %}
    {% include 'partials/backtotop.html.twig' %}
{% endif %}`

inside base.html.twig before ` </body>`. And button back to top visible, but when I click - nothing happened. 

I didn't check another themes, but mediator theme. Can anybody help. Test site - https://alfabuster.com

**Comment by marcosegato** [comment]
Try moving the code just before `<!-- footer end -->`, this should solve.

**Comment by alfabuster** [comment]
@marcosegato when i put code before `<!-- footer end -->` it is not showing at all. Maybe I choose wrong template for twig...

**Comment by alfabuster** [comment]
Yes, my fault this code I should put in the file post.html.twig not in base.html.twig, before code
`{% endblock %} {% block footer %}{% endblock %}`

Now it works great. Thank you for your help. Nice plugin!

**Comment by marcosegato** [comment]
So glad to hear it. Thanks! :)
