### ISSUE TITLE
Unable to see the icon after installing the plugin using GPM

### ISSUE THREAD

**Issue by bachurva** [marcosegato/grav-plugin-backtotop#6]
Hi

I have installed the plugin using GPM but I do not see the backtotop icon on either of my website pages.

I am using the Learn 2 Git Sync theme and I have the Problems plugin installed too.

Looked through the backtotop yaml file and all the fields are enabled.

Is there anything I am missing? Am I required to add anything to the pages for the icon to appear?

Kindly confirm. Thanks

**Comment by marcosegato** [comment]
Yes, you need to add few lines to your theme too: you can follow the instructions in the README file at [https://github.com/marcosegato/grav-plugin-backtotop#usage-for-theme-developers](https://github.com/marcosegato/grav-plugin-backtotop#usage-for-theme-developers)

**Comment by bachurva** [comment]
Thanks. Issue is fixed.
