### ISSUE TITLE
Suggestion to add title attribute to href

### ISSUE THREAD

**Issue by awrog** [marcosegato/grav-plugin-backtotop#8]
Nice plugin, especially with long pages.

Suggestion to add title attribute to href in backtotop.html.twig

<a href="#top" id="return-to-top" aria-label="Back to top" **title="Back to top"** >
This will display (upon hovering of the mouse)

![image](https://user-images.githubusercontent.com/12153667/206215273-3d2c6233-4901-4996-90e3-dd5fef4ed59a.png)

**Comment by marcosegato** [comment]
@awrog much appreciated, thanks for your contribution. New release is on the way.
